### ISSUE TITLE
Compile failed !!!

### ISSUE THREAD

**Issue by Droid-MAX** [ernesto-xload/ducky_interpreter#1]
![s70911-214130](https://user-images.githubusercontent.com/12762435/30277873-b2c7c792-96ce-11e7-96dd-8668d53a5109.jpg)

In the PC platform ArduinoIDE in the preparation of ducky_interpreter still failed, the error information is also consistent.

**Comment by ernesto-xload** [comment]
Hello Droid-MAX you need install and configure this library https://github.com/ernesto-xload/arduino_keyboardlib, some keys like print screen are not implemented in original Arduino Keyboard library.
