### ISSUE TITLE
The reason has been found and the problem is resolved

### ISSUE THREAD

**Issue by Droid-MAX** [ernesto-xload/ducky_interpreter#2]
![s70912-005010](https://user-images.githubusercontent.com/12762435/30287039-435e04c8-96e9-11e7-8d77-f5f0ce69ed9d.jpg)

Compiled only if comments or remove KEY_PRINTSCREEN and KEY_MENU snippet are successful.

**Comment by ernesto-xload** [comment]
KEY_MENU is a really useful key in pentesting ;) I highly recommend installing the library https://github.com/ernesto-xload/arduino_keyboardlib, It also support multiple keyboard layouts, not only en_US.
